Switch role validation from db check to from JWT contents
ably-labs/fully-featured-scalable-chat-app pull request #53
Opened 2022-01-05 16:46 UTC by tomczoink

We were previously checking the database each time we needed to validate if a user had the correct role to perform an action for an endpoint. This PR avoids that by instead attaching the roleName to the JWT a client will have, so that we can instead check the JWT's roleName field to ensure it matches.

This should eventually be swapped probably to have the JWT contain the permissions over just the roleName as that'll be more relevant, but that is for a later PR once we define and create permissions for roles.

2022-01-18 11:29 UTC, thisisjofrank reviewed
Looks great, apart from merge conflict

2022-02-02 11:19 UTC, marcduiker requested changes

2022-02-02 11:19 UTC, marcduiker commented on api/common/services/UserService.ts
> -      profileImgSmallUrl: userProfileImageSmallUrl,
We need both the `profileImgSmallUrl` and `profileImgLargeUrl` properties here. The `profileImgUrl` can be removed.

2022-02-02 12:04 UTC, marcduiker approved these changes
LGTM

2022-02-02 12:09 UTC, merged